export default () => {}
// "type": [
//     "default",
//     "color",
//     "date",
//     "datetime-local",
//     "email",
//     "hidden",
//     "image",
//     "month",
//     "number",
//     "password",
//     "radio",
//     "range",
//     "reset",
//     "tel",
//     "time",
//     "url",
//     "week"
// ],
